2025-03-08 22:52:10 - INFO - Starting redeployment process...
2025-03-08 22:52:22 - INFO - Deployment completed successfully!
2025-03-08 22:52:36 - INFO - Starting redeployment process...
2025-03-08 22:52:47 - INFO - Deployment completed successfully!
Traceback (most recent call last):
  File "/home/admin/venv/CarbonAware-Redeployment/redeploy-auto.py", line 40, in <module>
    logging.basicConfig(
  File "/usr/lib/python3.11/logging/__init__.py", line 2050, in basicConfig
    h = FileHandler(filename, mode,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/logging/__init__.py", line 1181, in __init__
    StreamHandler.__init__(self, self._open())
                                 ^^^^^^^^^^^^
  File "/usr/lib/python3.11/logging/__init__.py", line 1213, in _open
    return open_func(self.baseFilename, self.mode,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/redeploy.log'
